### PR TITLE
Adding data for Sitecom WL-302

### PR DESCRIPTION
**Pull request by bonfus**

### CODE REVIEW

**Comment by benhylau** [comment]
Another `rt2800usb` driver :)

This is like the Alfa one with only 2.4 GHz band. Can you also add it to this table please: https://github.com/phillymesh/802.11s-adapters#good-devices

**Comment by bonfus** [comment]
I can do that but I haven't tested `AdHoc` mode yet. I'll do that this evening.

**Comment by benhylau** [comment]
Thanks @bonfus 👍

**Comment by bonfus** [comment]
Setting `AdHoc` mode works:

```
$ sudo ip link set wlan1 down
$ sudo iw wlan1 set type ibss
$ sudo ip link set wlan1 up
$ sudo iw wlan1 ibss join bla 2432
$ iwconfig 
wlan1     IEEE 802.11  ESSID:"bla"  
          Mode:Ad-Hoc  Frequency:2.432 GHz  Cell: Not-Associated   
          Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off
```
Should I check also the whole install procedure or this is enough?

**Comment by benhylau** [comment]
I think this is good enough! Thank you

**Comment by darkdrgn2k** [comment]
I would check it actually works (see things In station dump)

orange pi zero will bring up a mesh interface but not actually do anything with it

**Comment by bonfus** [comment]
The mesh mode works, I've checked it with my other two PIs. It connects to the other two WN722N devices and I can see them as two neighbors in `yrd top`. I did not do the same test for the `AdHoc` though.

**Comment by darkdrgn2k** [comment]
ad-hoc not really tested on any of these devices so don't worry

**Review by benhylau — APPROVED** [review]

**Comment by benhylau** [comment]
Thanks for the PR @bonfus

**Pull request merged**
